version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb_container
    environment:
      - MONGO_INITDB_DATABASE=your-db-name
      - MONGO_INITDB_ROOT_USERNAME=your-db-username
      - MONGO_INITDB_ROOT_PASSWORD=your-db-password
    ports:
      - 27017:27017
    networks:
      - mongodb_network
    volumes:
      # seeding scripts
      - ./mongo-entrypoint:/docker-entrypoint-initdb.d
      - ./data:/data/db
      - ./data:/data/configdb
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
      - "xpack.security.enabled=true"
      - "xpack.security.authc.api_key.enabled=true"
      - "xpack.security.authc.token.enabled=true"
      - "ELASTIC_PASSWORD=password"
      - "action.destructive_requires_name=false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - mongodb_network
    ports:
      - 9200:9200
    volumes:
      - ./elastic-data:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    networks:
      - mongodb_network
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200

      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: CVLnj87HQTAuRX9=er95
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: c69548d9027afcf4d55146b1d425a9f4c69548d9027afcf4d55146b1d425a9f4

elastic-connectors:
    image: docker.elastic.co/enterprise-search/elastic-connectors:8.13.4.0
    depends_on:
      - elasticsearch
      - kibana
    volumes:
      - ./connectors-config:/config
    command: /app/bin/elastic-ingest -c /config/config.yml
    networks:
      - mongodb_network


networks:
  mongodb_network:
    driver: bridge

